name: Gitee Sync with Puppeteer
description: Gitee Sync with Puppeteer
author: sunn4room
branding:
  icon: upload-cloud
  color: red
inputs:
  username:
    required: true
  password:
    required: true
  repositories:
    required: true
runs:
  using: node20
  main: dist/index.js
