name: Gitee Sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        uses: sunn4room/gitee-sync@main
        with:
          username: sunn4room
          password: ${{ secrets.PASSWORD }}
          repositories: |
            sunn4mirror
